### ISSUE TITLE
Can't fetch from local 

### ISSUE THREAD

**Issue by estudiooka** [posthtml/posthtml-fetch#51]
/assets/data.json
`{
    "id": 1,
    "name": "Leanne Graham"
}
`

/index.html

```
<fetch url="./assets/data.json">
{{ response.name }}}
</fetch>
```

Returns:
ReferenceError: response is not defined

How to fetch a local json ?

**Comment by Scrum** [comment]
@estudiooka Hi, need more context on the issue.

I see a test that passes successfully 

https://github.com/posthtml/posthtml-fetch/blob/e387703bd6ed8277fde136c4e870172c1daea3d9/test/test.js#L82-L84
