### ISSUE TITLE
Can't use expressions plugin with it

### ISSUE THREAD

**Issue by cossssmin** [posthtml/posthtml-fetch#7]
So looking at `plugins.before` and `plugins.after`, I understand you can pass an array of PostHTML plugins to run before and after the remote content is fetched.

I'm trying to pass in `posthtml-expressions`, because I already have some variables in context, that I need to use inside the `<fetch>` tag:

```js
const fetch = require('posthtml-fetch')

module.exports = (html, config) => {
  // config is an object I already have
  const fetchPlugin = fetch({
    plugins: {
      before: [ expressions({locals: {page: config}}) ]
    }
  })
  
  return posthtml([fetchPlugin]).process(html).then(result => result.html)
}
```

At this point, I would expect both the `response` variable from `posthtml-fetch` and the `page` variable that I'm passing in `plugins.before` with `expressions` to be available.

I'll use a real example so you can reproduce it - imagine I already had `page.title` in context:

```html
<fetch url="https://css-tricks.com/wp-json/wp/v2/posts?page=1&per_page=7&offset=1&_embed=1">
  {{ page.title }}
  {{ response[0].title.rendered }}
</fetch>
```

This results in a `ReferenceError: page is not defined`

One way around it is if `posthtml-fetch` would accept a `locals` option.

However, I think passing in `expressions` with its own locals, before the content is fetched, should work. 

Am I missing something here?

**Comment by Scrum** [comment]
Hi, I got to this task https://github.com/posthtml/posthtml-fetch/issues/7, I found some problems that were fixed, but the question remains about `response` by a call 

before: [ expressions({locals: {page: config}}) ]

this value is not currently available and how would you like it to work ?

**Comment by cossssmin** [comment]
Imagine I already have an object with data that I want to make available to the `response` after it is fetched. So I may already have a variable, let's say `language` which equals `en`. 

With that, I should be able to do:

```html
<fetch url="...">
  {{ language }}
  <!-- now render response -->
  {{ response.title }}
</fetch>
```

... and get:

```html
en
<!-- now render response -->
response title text
```

If I do this now, I get an error because `language` is not defined when used inside the `<fetch>` tag, even though 'globally' it's available (i.e. outside the fetch tag).

Makes sense?

**Comment by Scrum** [comment]
I so believe that we need a mechanism that would tell expression what to process and what to process then so ?
